name: Merge - Preview and Prod

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

on: [pull_request]

jobs:
  deploy-preview:
    name: ðŸŽ Deploy preview
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: â¬‡ Checkout the branch
        uses: actions/checkout@v3

      - name: ðŸ’¿ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: â¬‡ Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ðŸ‘· Build Project Artifacts
        working-directory: project-5
        run: |
          vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }} && vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ðŸ— Build Project Artifacts to Vercel
        working-directory: project-5
        id: vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Staging
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE }}
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Get Preview URL
        run: echo "${{ steps.deploy-vercel-staging.outputs.preview-url }}" >> $GITHUB_STEP_SUMMARY
