name: Pull Request Check

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - 'feat/preview'

jobs:
  unit-test:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸš¦ Run Tests
        run: yarn test

  integration-test:
    name: ğŸ§© Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ‡¨ğŸ‡¾ Cypress run
        uses: ./.github/actions/cypress-run
        with:
          workdir: project-5

  type-checking:
    name: ğŸ”¬ Type checking
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ”¬ Type checking
        run: yarn typecheck

  deadcode-checking:
    name: ğŸ’€ Deadcode checking
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ’€ Deadcode checking
        run: |
          ${GITHUB_WORKSPACE}/.github/scripts/deadcode-check.sh
