name: Pull Request Check

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - 'feat/preview'

jobs:
  unit-test:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸš¦ Run Tests
        run: yarn test

  integration-test:
    name: ğŸ§© Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ‡¨ğŸ‡¾ Cypress run
        uses: ./.github/actions/cypress-run
        with:
          workdir: project-5

  type-checking:
    name: ğŸ”¬ Type checking
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ”¬ Type checking
        run: yarn typecheck

  deadcode-checking:
    name: ğŸ’€ Deadcode checking
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ’€ Deadcode checking
        run: |
          ${GITHUB_WORKSPACE}/.github/scripts/deadcode-check.sh

  deploy-preview:
    name: ğŸ Deploy preview
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - integration-test
      - type-checking
      - deadcode-checking
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: â¬‡ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ’¿ Install Vercel CLI
        run: npm install --global vercel@latest

      - name: â¬‡ Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ‘· Build Project Artifacts
        working-directory: project-5
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸ— Build Project Artifacts to Vercel
        working-directory: project-5
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
