name: Pull Request Check

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

on:
  pull_request:
    types: [review_requested]
  push:
    branches:
      - 'config/gha-unit-tests'

jobs:
  unit-test:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ—ƒ Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/project-5/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/project-5/yarn.lock') }}

      - name: ğŸ›  Install dependencies
        working-directory: project-5
        run: yarn

      - name: ğŸš¦ Run Tests
        run: yarn test:ci
