name: Pull Request Check

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

on:
  pull_request:
    types: [review_requested]
  push:
    branches:
      - 'config/gha-unit-tests'

jobs:
  unit-test:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - run: pwd

      - name: ğŸ—ƒ Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: ğŸ›  Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: ğŸš¦ Run Tests
        run: yarn test
