name: Pull Request Check

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

on: [pull_request]

jobs:
  unit-test:
    name: ğŸ§ª Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸš¦ Run Tests
        run: yarn test

  integration-test:
    name: ğŸ§© Integration Tests
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - run: pwd

      - name: ğŸ‡¨ğŸ‡¾ Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: project-5/
          install: false
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'

  type-checking:
    name: ğŸ”¬ Type checking
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ”¬ Type checking
        run: yarn typecheck

  deadcode-checking:
    name: ğŸ’€ Deadcode checking
    runs-on: ubuntu-latest
    env:
      working-directory: project-5
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: â¬‡ï¸ Checkout the branch
        uses: actions/checkout@v3

      - name: ğŸ›  Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          workdir: project-5

      - name: ğŸ’€ Deadcode checking
        run: |
          ${GITHUB_WORKSPACE}/.github/scripts/deadcode-check.sh
